[tool.black]
target-version = ['py37', 'py38', 'py39']

[tool.mypy]
python_version = "3.7"
ignore_missing_imports = true
scripts_are_modules = true
warn_unused_configs = true
show_error_codes = true
allow_redefinition = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rs --cov=./dic2owl/dic2owl/ --cov-report=term"
filterwarnings = [
    "ignore:.*imp module.*:DeprecationWarning",
]
