name: CI tests

on: [push, pull_request]

jobs:

  emmocheck:
    name: EMMOcheck
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install EMMO-python
      run: |
        while IFS="" read -r line || [ -n "${line}" ]; do
            if [[ "${line}" =~ ^EMMO.*$ ]]; then
                EMMO="${line}"
            fi
        done < dic2owl/requirements.txt

        pip install ${EMMO}

    - name: Check EMMO
      run: emmocheck --verbose --skip test_class_label ontology/cif_top.ttl
